### ISSUE TITLE
Test folder not included

### ISSUE THREAD

**Issue by nimi0112** [jorgecoca/calculator_app#3]
Hi @jorgecoca  thank you for the awesome course. I had watched it earlier on Caster.io and again watched it on YouTube today.

I was looking for the tests folder in this project and cannot find it here.

Since the testing course bought user's here it would be very good to upload that also.

**Comment by jorgecoca** [comment]
Hi @nimi0112 👋 

This project as the tests in different branches. There's a new different branch in the project with each one of the videos we published on YouTube.

![Screen Shot 2021-05-25 at 11 28 37 AM](https://user-images.githubusercontent.com/3237451/119534307-5f5c9800-bd4c-11eb-9ee7-8299f5072cb7.png)

I'll close this issue. Thank you!

**Comment by nimi0112** [comment]
Damn! I did not notice this, Can you please add this to Readme file ? @jorgecoca
